"""Matte the generated magenta sources and embed the two boot-page cutouts.

Requires Pillow, NumPy and OpenCV. Run from any directory after replacing
characters-magenta.png with the approved two-character source image.
"""
from base64 import b64encode
from pathlib import Path

import cv2
import numpy as np
from PIL import Image


root = Path(__file__).resolve().parent
exports = ['// Generated by assets/boot-error/prepare.py.']
sheet = Image.open(root / 'characters-magenta.png').convert('RGB')
midpoint = sheet.width // 2
for side in ('left', 'right'):
    bounds = (0, 0, midpoint, sheet.height) if side == 'left' else (midpoint, 0, sheet.width, sheet.height)
    original = np.asarray(sheet.crop(bounds))
    rgb = original.astype(np.float32)
    dominance = np.minimum(rgb[:, :, 0], rgb[:, :, 2]) - rgb[:, :, 1]
    key = ((rgb[:, :, 0] > 180) & (rgb[:, :, 2] > 180) & (rgb[:, :, 1] < 70)).astype(np.uint8)
    edge = cv2.dilate(key, np.ones((5, 5), np.uint8)).astype(bool)
    alpha = np.ones(dominance.shape, dtype=np.float32)
    alpha[edge] = np.clip((235 - dominance[edge]) / 215, 0, 1)
    alpha[key.astype(bool)] = 0
    # Unmix magenta only along the keyed boundary; opaque costume pixels
    # remain unchanged, including the white apron and frills.
    partial = (alpha > 0) & (alpha < 1)
    a = alpha[partial, None]
    rgb[partial] = (rgb[partial] - (1 - a) * np.array([255, 0, 255])) / a
    rgb[alpha == 0] = 0
    rgba = np.dstack((np.clip(rgb, 0, 255).astype(np.uint8), np.rint(alpha * 255).astype(np.uint8)))
    cutout = Image.fromarray(rgba)
    output = root / f'{side}.webp'
    cutout.save(output, quality=92, method=6, exact=True)
    embedded = b64encode(output.read_bytes()).decode('ascii')
    exports.append(f"export const MAID_BOOT_ERROR_{side.upper()} = 'data:image/webp;base64,{embedded}'")
    opaque = alpha == 1
    assert np.array_equal(rgba[opaque, :3], original[opaque])
    assert np.all(rgba[0, :, 3] == 0) and np.all(rgba[-1, :, 3] == 0)
    assert np.all(rgba[:, 0, 3] == 0) and np.all(rgba[:, -1, 3] == 0)
    print(f'{side}: {cutout.size}, {output.stat().st_size} bytes, transparent margin verified')

(root.parents[1] / 'src/client/boot-error-art.generated.ts').write_text('\n'.join(exports) + '\n', encoding='utf-8')
